name: Build and Push Docker image

#on:
#  push:
#    branches:
#      - main  # Trigger the workflow on push to the main branch
#      - dev_server
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v2
#
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v1
#
#    - name: Login to DockerHub
#      uses: docker/login-action@v1
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#    - name: Build and push Docker image
#      uses: docker/build-push-action@v2
#      with:
#        context: ./
#        file: ./${{ github.ref == 'refs/heads/main' && 'Dockerfile' || 'Dockerfile_dev' }}
#        push: true
#        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.ref == 'refs/heads/main' && 'erp' || 'arialpha_dev' }}:latest

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
      - test


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract branch name and version
      id: prep
      run: |
        echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
        VERSION_TAG=${GITHUB_REF/refs\/tags\//}
        echo ::set-output name=version::${VERSION_TAG}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./${{ github.ref == 'refs/heads/main' && 'Dockerfile' || 'Dockerfile_dev' }}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.ref == 'refs/heads/main' && 'erp' || 'arialpha_dev' }}:${{ github.run_number }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.ref == 'refs/heads/main' && 'erp' || 'arialpha_dev' }}:latest
